services:
  postgres:
    image: postgres:16
    container_name: food-recipes-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: food_recipes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - food-recipes-db:/var/lib/postgresql/data

volumes:
  food-recipes-db:
